# Generated by Django 3.2.7 on 2021-09-02 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Nombre', max_length=50, null=True)),
                ('dateupload', models.DateTimeField(db_column='Fecha de subida', default=django.utils.timezone.now)),
                ('portada', models.ImageField(db_column='Portada', upload_to='portadaspelis')),
                ('director', models.CharField(db_column='Director', max_length=100, null=True)),
                ('descipcion', models.TextField(db_column='Descripcion', max_length=1000, null=True)),
            ],
        ),
    ]
